name: CI
on:
  push:
    branches:
      - main
  # eslint-disable-next-line yml/no-empty-mapping-value
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup node and pnpm
        uses: ./.github/actions/setup

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm vitest

      - name: Build
        run: pnpm build
